[env:simple_bridge_esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
framework = espidf
build_flags = 
	-D_PORT_TYPE_UINT32
  -DDISABLE_WEB_SERVER
  -DJSMN_STATIC
board_build.flash_mode = dio
upload_protocol = esp-builtin
; board_upload.before_reset = usb_reset
; upload_port = COM5
extra_scripts = pre:scripts/pre_script.py
debug_tool = esp-builtin
build_type = debug
debug_build_flags = -O0 -g -ggdb
; build_src_filter = 
; 	-<*> 
; 	+<receiver_esp32c3/*>

lib_deps = 
  symlink://../../lib/spi_custom
  symlink://../../lib/nrf24
  symlink://../../lib/sensor_packet
  symlink://../../lib/utils_lib
  symlink://../../lib/jsmn
  https://github.com/joltwallet/esp_littlefs.git
  
monitor_speed = 115200
monitor_raw = true