; This configuration is used for test PCB for Simple Weather Sensor with:
; - BME280 or BME680
; - ADC
; - nrf24
; - SL2301 - sleep timer
[env:SimpleWeatherSensorBMP280]
platform = atmelavr
board = attiny2313
board_build.mcu = attiny2313a
board_build.f_cpu = 8000000L
build_flags = 
	-DATTINY2313A
	-DSENSOR
	-DSIMPLE_WEATHER_SENSOR
	-DTEST_PCB
	-DNO_SLEEP_TIMER
	-DUSING_SENSOR_BMP280
	; -DUSING_SENSOR_BME280
	; -DUSING_SENSOR_BME280
	-std=c++17
	-Os
	-D_PORT_TYPE_UINT8
build_unflags = -std=c++11
; build_src_filter = 
	; -<*> 
	; +<sensor_attiny2313/*>
lib_deps = 
  symlink://../../lib/spi_custom
  symlink://../../lib/nrf24
  symlink://../../lib/bmelib
  symlink://../../lib/sensor_packet
  symlink://../../lib/utils_lib
upload_protocol = custom
upload_port = usb
; upload_speed = 9600
board_fuses.lfuse = 0xe4
board_fuses.hfuse = 0xDf
upload_flags = 
	-C
	${platformio.packages_dir}/tool-avrdude/avrdude.conf
	-p
	t2313
	-P
	$UPLOAD_PORT
	; -b
	; $UPLOAD_SPEED
	; -e
	-c
	usbasp
	; -B0.25
upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i -U eeprom:w:"src\sensor_attiny2313\eeprom_attiny2313a.eep":r

[env:SimpleWeatherSensorBME280]
platform = atmelavr
board = attiny2313
board_build.mcu = attiny2313a
board_build.f_cpu = 8000000L
build_flags = 
	-DATTINY2313A
	-DSENSOR
	-DSIMPLE_WEATHER_SENSOR
	-DTEST_PCB
	; -DNO_SLEEP_TIMER
	; -DENABLE_BUTTON_MEASUREMENT
	; -DUSING_SENSOR_BMP280
	-DUSING_SENSOR_BME280
	; -DUSING_SENSOR_BME280
	-std=c++17
	-Os
	-D_PORT_TYPE_UINT8
build_unflags = -std=c++11
; build_src_filter = 
; 	-<*> 
; 	+<sensor_attiny2313/*>
lib_deps = 
  symlink://../../lib/spi_custom
  symlink://../../lib/nrf24
  symlink://../../lib/bmelib
  symlink://../../lib/sensor_packet
  symlink://../../lib/utils_lib
upload_protocol = custom
upload_port = usb
; upload_speed = 9600
board_fuses.lfuse = 0xe4
board_fuses.hfuse = 0xDf
upload_flags = 
	-C
	${platformio.packages_dir}/tool-avrdude/avrdude.conf
	-p
	t2313
	-P
	$UPLOAD_PORT
	; -b
	; $UPLOAD_SPEED
	; -e
	-c
	usbasp
	; -B0.25
upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i -U eeprom:w:"src\eeprom_attiny2313a.eep":r

[env:SimpleWeatherSensorBME680]
platform = atmelavr
board = attiny4313
board_build.mcu = attiny4313a
build_flags = 
	-DATTINY2313A
	-DSENSOR
	-DSIMPLE_WEATHER_SENSOR
	-DTEST_PCB
	-DNO_SLEEP_TIMER
	; -DUSING_SENSOR_BMP280
	; -DUSING_SENSOR_BME280
	-DUSING_SENSOR_BME280
	-std=c++17
	-Os
	-D_PORT_TYPE_UINT8
build_unflags = -std=c++11
build_src_filter = 
	-<*> 
	+<sensor_attiny2313/*>
board_build.f_cpu = 8000000L
upload_protocol = custom
upload_port = usb
; upload_speed = 9600
board_fuses.lfuse = 0xe4
board_fuses.hfuse = 0xDf
upload_flags = 
	-C
	${platformio.packages_dir}/tool-avrdude/avrdude.conf
	-p
	t2313
	-P
	$UPLOAD_PORT
	; -b
	; $UPLOAD_SPEED
	; -e
	-c
	usbasp
	; -B0.25
upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i -U eeprom:w:"src\sensor_attiny2313\eeprom_attiny2313a.eep":r
