; This configuration is used for test PCB for Simple Weather Sensor with:
; - BME280 or BME680
; - ADC
; - nrf24
; - SL2301 - sleep timer
[env:SimpleWeatherSensorTestPCB]
platform = atmelavr
board = attiny2313
board_build.mcu = attiny2313a
build_flags = 
	-DATTINY2313A
	-DSENSOR
	-DSIMPLE_WEATHER_SENSOR
	-DTEST_PCB
	-DNO_SLEEP_TIMER
	-DUSING_SENSOR_BMP280
	; -DUSING_SENSOR_BME280
	-std=c++17
	-Os
	-D_PORT_TYPE_UINT8
build_unflags = -std=c++11
build_src_filter = 
	-<*> 
	+<sensor_attiny2313/*>
board_build.f_cpu = 8000000L
upload_protocol = custom
upload_port = usb
; upload_speed = 9600
board_fuses.lfuse = 0xe4
board_fuses.hfuse = 0xDf
upload_flags = 
	-C
	${platformio.packages_dir}/tool-avrdude/avrdude.conf
	-p
	t2313
	-P
	$UPLOAD_PORT
	; -b
	; $UPLOAD_SPEED
	; -e
	-c
	usbasp
	; -B0.25
upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i -U eeprom:w:"src\attiny2313\eeprom_attiny2313a.eep":r


[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = picosdk
upload_protocol = cmsis-dap
build_flags = 
	-DRP2040
	-std=c++17
	; -DPIO_NO_STDIO_UART
	-DWEATHER_RECEIVER
	-D_PORT_TYPE_UINT32
build_src_filter = 
	-<*> 
	+<rp2040/*>
debug_tool = cmsis-dap
debug_speed = 10000
build_type = debug

[env:native_receiver]
platform = native
build_flags = 
	-DWEATHER_RECEIVER
	-DNATIVE
	; -Ilib/nrf24/include
	; -Llib/nrf24
	; -lnrf24
	-D_PORT_TYPE_UINT32
	-std=c++17
build_src_filter = 
	-<*> 
	+<native_receiver/*>
debug_test = test_native
lib_archive = false
; lib_compat_mode = off
; test_framework = googletest
lib_deps = 
	; google/googletest@^1.15.2
    nrf24
test_build_src = true